# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1RpsphrpNQ9QPXnHiDtmhJoNM4qsRyh
"""

!pip install -q --upgrade mediapipe
!wget -q -O /content/face_landmarker.task https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task
print("✓ מוכן")

import glob
print("וידאו:", glob.glob("/content/*.mp4"))
print("JSON:", glob.glob("/content/*.json"))
print("מודל:", glob.glob("/content/face_landmarker.task"))




#  קוד עם פלט של 7 מתוך 7
# ============================================================
#  זיהוי תנועת שפתיים — צוות 4  |  גרסה סופית + חיבור לצוות הפנים
#
#  הקלט: וידאו + faces_output.json מצוות זיהוי הפנים (Team 3)
#        (תיבות מנורמלות 0-1 + face_id יציב לכל משתתף)
#  הפלט: לכל face_id — האם דיבר (לפי שונות פתיחת הפה MAR)
#
#  אין יותר SimpleTracker — ה-face_id מגיע מצוות הפנים.
#  הליבה (MAR) זהה למה שבנינו; רק מקור התיבות התחלף.
# ============================================================
import cv2, json, glob, numpy as np
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

STD_THRESHOLD = 0.035        # שונות MAR מעל זה => דיבר (לכייל לפי הדירוג)
MODEL = "/content/face_landmarker.task"
UPPER, LOWER, LEFT, RIGHT = 13, 14, 61, 291

def mouth_aspect_ratio(lm, w, h):
    pt = lambda i: np.array([lm[i].x * w, lm[i].y * h])
    return np.linalg.norm(pt(UPPER) - pt(LOWER)) / (np.linalg.norm(pt(LEFT) - pt(RIGHT)) + 1e-6)

def make_landmarker():
    opts = vision.FaceLandmarkerOptions(
        base_options=python.BaseOptions(model_asset_path=MODEL),
        num_faces=1, running_mode=vision.RunningMode.IMAGE)
    return vision.FaceLandmarker.create_from_options(opts)

def load_face_boxes(json_path):
    """frame_index -> [(face_id, x,y,w,h normalized)] מתוך הפלט של צוות הפנים."""
    data = json.load(open(json_path))
    by_frame = {}
    for fr in data["frames"]:
        by_frame[fr["frame_index"]] = [
            (f["face_id"], f["bounding_box"]["x_min"], f["bounding_box"]["y_min"],
             f["bounding_box"]["width"], f["bounding_box"]["height"])
            for f in fr["faces_detected"]]
    return by_frame, data.get("total_participants_detected")

def analyze(video_path, boxes_by_frame, frame_skip=5, pad=0.30):
    cap = cv2.VideoCapture(video_path)
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    lm = make_landmarker()
    series, idx = {}, 0
    while True:
        ok, frame = cap.read()
        if not ok:
            break
        if idx % frame_skip == 0 and idx in boxes_by_frame:
            if idx % 2000 == 0:
                print(f"  מעבד... {idx}/{total}")
            H, W = frame.shape[:2]
            for fid, xn, yn, wn, hn in boxes_by_frame[idx]:
                x, y, w, h = xn * W, yn * H, wn * W, hn * H      # נורמלי -> פיקסלים
                px, py = w * pad, h * pad                         # ריווח סביב הפרצוף
                crop = frame[max(0, int(y - py)):min(H, int(y + h + py)),
                             max(0, int(x - px)):min(W, int(x + w + px))]
                if crop.size == 0:
                    continue
                rgb = cv2.cvtColor(crop, cv2.COLOR_BGR2RGB)
                res = lm.detect(mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb))
                if res.face_landmarks:
                    ch, cw = crop.shape[:2]
                    series.setdefault(fid, []).append(
                        mouth_aspect_ratio(res.face_landmarks[0], cw, ch))
        idx += 1
    cap.release()
    return series

# ---- הרצה ----
mp4s = [f for f in glob.glob("/content/**/*.mp4", recursive=True) if "sample_data" not in f]
jsons = glob.glob("/content/**/faces_output.json", recursive=True) or glob.glob("/content/*.json")
assert mp4s and jsons, "❌ צריך גם MP4 וגם faces_output.json תחת /content"
VIDEO, JSON = mp4s[0], jsons[0]
print("✓ וידאו:", VIDEO, "\n✓ תיבות:", JSON)

boxes_by_frame, total_participants = load_face_boxes(JSON)
series = analyze(VIDEO, boxes_by_frame)

print(f"\n{'face_id':<10}{'std':<10}{'frames':<9}{'מדבר?'}")
speaking = 0
for fid in sorted(series):
    std = float(np.std(series[fid]))
    sp = std > STD_THRESHOLD
    speaking += sp
    print(f"{fid:<10}{round(std,4):<10}{len(series[fid]):<9}{'✅ מדבר' if sp else '— שותק'}")

print(f"\nמשתתפים בסך הכל (מצוות הפנים): {total_participants}")
print(f"מדברים (לפי תנועת שפתיים):     {speaking}")








#  קוד עם פלט של 6 מתוך 7
# ============================================================
#  זיהוי תנועת שפתיים — צוות 4  (קוד סופי יחיד)
# ============================================================
#  מה הקוד עושה:
#    מקבל וידאו + faces_output.json מצוות זיהוי הפנים (תיבות + face_id),
#    מודד לכל משתתף את פתיחת הפה (MAR) לאורך הזמן, ומחליט מי דיבר
#    לפי אנרגיה בתחום תדרי הדיבור (כך שחיוך/ניד-ראש אינם נספרים).
#
#  קלט (להעלות ל-/content):  הוידאו (mp4) + faces_output.json
#  פלט:  לכל face_id — דיבר/לא, ומספר הדוברים הכולל.
#
#  הרצה ב-Colab:
#    תא 1:  !pip install -q --upgrade mediapipe
#           !wget -q -O /content/face_landmarker.task \
#             https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task
#    תא 2:  כל הקוד הזה.
# ============================================================
import cv2, json, glob, numpy as np
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

# ---------------- פרמטרים לכיול ----------------
SPEECH_THRESHOLD = 300.0      # אנרגיית-דיבור מעל זה => דיבר (כוונן לפי הדירוג שמודפס)
FRAME_SKIP       = 3          # 3 = איזון טוב | 2 = מדויק/איטי | 4 = מהיר
SPEECH_LO, SPEECH_HI = 1.5, 6.0   # תחום תדרי דיבור (הרץ)
MODEL = "/content/face_landmarker.task"
UPPER, LOWER, LEFT, RIGHT = 13, 14, 61, 291   # נקודות שפתיים (Face Landmarker)
# ------------------------------------------------


def mouth_aspect_ratio(lm, w, h):
    """יחס פתיחת הפה: מרחק אנכי בין השפתיים חלקי רוחב הפה (מנורמל למרחק)."""
    pt = lambda i: np.array([lm[i].x * w, lm[i].y * h])
    return np.linalg.norm(pt(UPPER) - pt(LOWER)) / (np.linalg.norm(pt(LEFT) - pt(RIGHT)) + 1e-6)


def speech_power(sig, fs):
    """אנרגיה מוחלטת בתחום תדרי הדיבור. דיבור=תנודה מהירה->גבוה;
    חיוך/ניד-ראש=שינוי איטי->מתחת לתחום; שתיקה=רעש חלש->נמוך."""
    sig = np.asarray(sig, float)
    if len(sig) < 32:
        return 0.0
    sig = sig - sig.mean()
    freqs = np.fft.rfftfreq(len(sig), 1 / fs)
    power = np.abs(np.fft.rfft(sig)) ** 2
    hi = min(SPEECH_HI, fs / 2 * 0.95)          # לא לעבור את תדר נייקוויסט
    return float(power[(freqs >= SPEECH_LO) & (freqs <= hi)].sum() / len(sig) * 1000)


def make_landmarker():
    opts = vision.FaceLandmarkerOptions(
        base_options=python.BaseOptions(model_asset_path=MODEL),
        num_faces=1, running_mode=vision.RunningMode.IMAGE)
    return vision.FaceLandmarker.create_from_options(opts)


def load_face_boxes(json_path):
    """טוען את פלט צוות הפנים: frame_index -> [(face_id, x,y,w,h מנורמל)]."""
    data = json.load(open(json_path))
    by_frame = {fr["frame_index"]: [
        (f["face_id"], f["bounding_box"]["x_min"], f["bounding_box"]["y_min"],
         f["bounding_box"]["width"], f["bounding_box"]["height"])
        for f in fr["faces_detected"]] for fr in data["frames"]}
    return by_frame, data.get("total_participants_detected"), data.get("fps", 30)


def measure_mar(video, boxes_by_frame, pad=0.30):
    """מחזיר {face_id: [סדרת MAR לאורך הזמן]} — שלב הניתוח הכבד."""
    cap = cv2.VideoCapture(video)
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    lm = make_landmarker()
    series, idx = {}, 0
    while True:
        ok, frame = cap.read()
        if not ok:
            break
        if idx % FRAME_SKIP == 0 and idx in boxes_by_frame:
            if idx % 3000 == 0:
                print(f"  מעבד... {idx}/{total}")
            H, W = frame.shape[:2]
            for fid, xn, yn, wn, hn in boxes_by_frame[idx]:
                x, y, w, h = xn * W, yn * H, wn * W, hn * H
                px, py = w * pad, h * pad           # ריווח סביב התיבה לזיהוי טוב יותר
                crop = frame[max(0, int(y - py)):min(H, int(y + h + py)),
                             max(0, int(x - px)):min(W, int(x + w + px))]
                if crop.size == 0:
                    continue
                res = lm.detect(mp.Image(image_format=mp.ImageFormat.SRGB,
                                         data=cv2.cvtColor(crop, cv2.COLOR_BGR2RGB)))
                if res.face_landmarks:
                    ch, cw = crop.shape[:2]
                    series.setdefault(fid, []).append(
                        mouth_aspect_ratio(res.face_landmarks[0], cw, ch))
        idx += 1
    cap.release()
    return series


def report(series, fs, total_participants, threshold=SPEECH_THRESHOLD):
    """שלב הכיול — מהיר. אפשר לקרוא שוב עם סף אחר בלי לנתח מחדש."""
    scored = sorted(((fid, speech_power(s, fs)) for fid, s in series.items()),
                    key=lambda kv: -kv[1])
    print(f"\n{'face_id':<10}{'אנרגיית-דיבור':<16}{'מדבר?'}")
    speaking = 0
    for fid, sp in scored:
        is_sp = sp > threshold
        speaking += is_sp
        print(f"{fid:<10}{round(sp, 1):<16}{'✅ מדבר' if is_sp else '— שותק'}")
    print(f"\nמשתתפים בסך הכל (מצוות הפנים): {total_participants}")
    print(f"מדברים (לפי תנועת שפתיים):     {speaking}")
    return speaking


# ==================== הרצה ====================
mp4s  = [f for f in glob.glob("/content/**/*.mp4", recursive=True) if "sample_data" not in f]
jsons = glob.glob("/content/**/faces_output.json", recursive=True) or glob.glob("/content/*.json")
assert mp4s and jsons, "❌ צריך גם MP4 וגם faces_output.json תחת /content"
VIDEO, JSON = mp4s[0], jsons[0]
print("✓ וידאו:", VIDEO, "\n✓ תיבות:", JSON)

boxes_by_frame, total_participants, fps = load_face_boxes(JSON)
fs = fps / FRAME_SKIP                      # קצב דגימה אפקטיבי
print(f"קצב דגימה: {fs:.1f}Hz | תחום דיבור: {SPEECH_LO}-{min(SPEECH_HI, fs/2*0.95):.1f}Hz")

series = measure_mar(VIDEO, boxes_by_frame)   # ניתוח כבד (פעם אחת)
report(series, fs, total_participants);         # דוח + כיול

# ---- לכיול מחדש בלי להריץ את הניתוח שוב, פשוט הריצי בתא נפרד: ----
#   report(series, fs, total_participants, threshold=350)